kind: Deployment
apiVersion: apps/v1
metadata:
   name: naveen
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: naveen
   template:
      metadata:
        labels:
          app: naveen
      spec:
       containers:
        - name: naveen
          image: naveen2911/pipeline-demo
          imagePullPolicy: Always
          ports:
          - containerPort: 80
