kind: Service                             
apiVersion: v1
metadata:
  name: naveen
  labels:
    app: naveen
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: naveen                  
  type: LoadBalancer                   
