kind: Service                             
apiVersion: v1
metadata:
  name: naveen
  labels:
    app: naveen
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080     
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: naveen                  
  # type: LoadBalancer                   
